import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const label=process.argv[2]||'before',out='artifacts/lag-profile';await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome'}),page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.__uploads={calls:0,ms:0,atlas:0};for(const name of ['texImage2D','texSubImage2D']){const orig=WebGL2RenderingContext.prototype[name];WebGL2RenderingContext.prototype[name]=function(...args){const start=performance.now(),result=orig.apply(this,args),src=args.find(a=>a instanceof HTMLCanvasElement);window.__uploads.calls++;window.__uploads.ms+=performance.now()-start;if(src?.width===2560&&src?.height===1408)window.__uploads.atlas++;return result;}}});
await page.goto('http://127.0.0.1:4196/battleship/');await page.waitForFunction(()=>window.__THREE_GAME_TEST_HOOKS__?.getState().texturesReady,{},{timeout:60000});await page.waitForTimeout(1500);
const cdp=await page.context().newCDPSession(page),results={};
async function measure(name,orbit=false){await page.waitForTimeout(600);await cdp.send('Profiler.enable');await cdp.send('Profiler.start');const frames=await page.evaluate(orbit=>new Promise(resolve=>{window.__uploads={calls:0,ms:0,atlas:0};const c=document.getElementById('game-canvas'),x=960,y=400;let a=[],prev; if(orbit)c.dispatchEvent(new PointerEvent('pointerdown',{pointerId:1,pointerType:'mouse',button:0,buttons:1,clientX:x,clientY:y,bubbles:true}));function tick(now){if(prev!==undefined)a.push(now-prev);prev=now;if(orbit)c.dispatchEvent(new PointerEvent('pointermove',{pointerId:1,pointerType:'mouse',buttons:1,clientX:x+a.length*.4,clientY:y,bubbles:true}));if(a.length<180)requestAnimationFrame(tick);else{if(orbit)c.dispatchEvent(new PointerEvent('pointerup',{pointerId:1,pointerType:'mouse',button:0,buttons:0,clientX:x+a.length*.4,clientY:y,bubbles:true}));a.sort((a,b)=>a-b);resolve({mean:a.reduce((a,b)=>a+b,0)/a.length,p50:a[90],p95:a[171],max:a.at(-1),over33:a.filter(x=>x>33.5).length,uploads:window.__uploads});}}requestAnimationFrame(tick)}),orbit);const {profile}=await cdp.send('Profiler.stop');await writeFile(`${out}/${label}-${name}-cpu.json`,JSON.stringify(profile));const counts=new Map();for(const id of profile.samples??[])counts.set(id,(counts.get(id)??0)+1);const hot=profile.nodes.map(n=>({name:n.callFrame.functionName,line:n.callFrame.lineNumber,count:counts.get(n.id)??0})).sort((a,b)=>b.count-a.count).slice(0,20);results[name]={frames,hot,state:await page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.getState())};console.log(name,JSON.stringify({frames,hot:hot.slice(0,10),renderer:results[name].state.renderer}));}
await measure('fleet');await page.locator('#start-game').click();await page.keyboard.press('Space');await page.waitForFunction(()=>!window.__THREE_GAME_TEST_HOOKS__.getState().camera.focusing);await measure('inspect');await measure('orbit',true);await writeFile(`${out}/${label}.json`,JSON.stringify({results,errors},null,2));await browser.close();
