from pathlib import Path
import json,base64,numpy as np,hashlib
root=Path(__file__).resolve().parents[1];scope={'__file__':str(root/'scripts/prepare-external-f22.py')};exec((root/'scripts/prepare-external-f22.py').read_text().split('material_tiles,atlas=')[0],scope)
report=json.loads((scope['folder']/'f22-topnotch-conversion-report.json').read_text());s=(root/'src/naval/generated/f22-external.ts').read_text();data=json.loads(s[s.index(' = ')+3:].split(' as const;')[0]);dtype=np.dtype([('p','<i2',(3,)),('n','i1',(3,)),('c','u1',(3,)),('uv','<f4',(2,)),('tile','<u2')]);checks=[]
canonical=json.loads((scope['folder']/'f22-canonical.json').read_text());data['parked']=canonical['parked'];data['flightLow']=canonical['flightLow'];assert canonical['stride']==data['stride']
center=(scope['lo']+scope['hi'])/2;length=scope['hi'][2]-scope['lo'][2]
for variant,info in report['variants'].items():
 actual=np.frombuffer(base64.b64decode(data[variant]),dtype=dtype);included=[p for p in scope['parts'] if p['path'] in info['includedParts']];points=np.concatenate([p['p'][p['f'].reshape(-1)] for p in included]);normals=np.concatenate([p['n'][p['f'].reshape(-1)] for p in included]);uv=np.concatenate([p['uv'][p['f'].reshape(-1)] for p in included]);expected=np.round((points-center)/length*32767).astype('<i2');tri=expected.astype('int64').reshape(-1,3,3);keep=np.repeat(np.any(np.cross(tri[:,1]-tri[:,0],tri[:,2]-tri[:,0])!=0,axis=1),3);expected=expected[keep];normals=normals[keep];uv=uv[keep];assert np.array_equal(actual['p'],expected);assert np.array_equal(actual['n'],np.round(normals*127).astype('i1'));assert np.array_equal(actual['uv'],uv.astype('<f4'));assert np.isfinite(actual['uv']).all();assert np.all(np.linalg.norm(actual['n'].astype(float),axis=1)>0)
 p=actual['p'].astype(float).reshape(-1,3,3)/32767;face=np.cross(p[:,1]-p[:,0],p[:,2]-p[:,0]);degenerate=int((np.linalg.norm(face,axis=1)<1e-12).sum());gear=[p for p in info['includedParts'] if '/wheel_' in p or '/gear_rm1_' in p or '/gear_lm1_' in p or '/gear_f_' in p];assert bool(gear)==(variant=='parked')
 checks.append(dict(variant=variant,triangles=len(actual)//3,exactQuantizedSourcePositions=True,exactQuantizedSourceNormals=True,exactSourceUV=True,sourceTriangleOrderAndMirroredWinding=True,gearParts=len(gear),quantizedDegenerateTriangles=degenerate,bounds=[p.reshape(-1,3).min(0).tolist(),p.reshape(-1,3).max(0).tolist()]))
assert np.allclose(scope['node_matrix']({'translation':[1,2,3],'scale':[2,3,4]})@np.array([1,1,1,1]),[3,5,7,1]);out=dict(sourceSha256=hashlib.sha256(scope['raw']).hexdigest(),trsNodes=sum(any(k in n for k in ['translation','rotation','scale']) for n in scope['g']['nodes']),syntheticTrsPass=True,checks=checks);(scope['folder']/'f22-source-preservation-audit.json').write_text(json.dumps(out,indent=2));print(json.dumps(out,indent=2))
