import test from 'node:test';import assert from 'node:assert/strict';import {GameDatabase} from '../db.js';import {ITEMS} from '../../shared/catalog.ts';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
const catalog={byId:new Map(ITEMS.map(i=>[i.id,i])),talents:[]};
function fixture(path=':memory:',random=()=>.9){const db=new GameDatabase(path,{lossRandom:random});db.instanceCatalog=catalog.byId;const u=db.createUser('instance-user',Buffer.from('s'),Buffer.from('h'),[{itemId:'m416',quantity:2},{itemId:'red-dot',quantity:2},{itemId:'armor-6',quantity:2}],{primary:'m416',armor:'armor-6'});return {db,u};}
test('duplicate firearms keep independent durable fittings through swaps and host-only sale',()=>{const dir=mkdtempSync(join(tmpdir(),'penguin-instances-')),path=join(dir,'save.sqlite');let db;try{const f=fixture(path);db=f.db;const u=f.u,id=u.id;const p=db.profile(id),first=p.equippedInstanceIds.primary,second=p.instances.find(r=>r.itemId==='m416'&&r.id!==first).id;db.equip(id,'primary:scope','red-dot',catalog,null,first);db.equip(id,'primary','m416',catalog,second);assert.equal(db.profile(id).equipped['primary:scope'],undefined);assert.equal(db.reservedQuantity(id,'red-dot'),1);db.equip(id,'primary:scope','red-dot',catalog,null,second);assert.equal(db.reservedQuantity(id,'red-dot'),2);db.equip(id,'primary','m416',catalog,first);assert.equal(db.profile(id).equipped['primary:scope'],'red-dot');db.close();db=new GameDatabase(path);db.instanceCatalog=catalog.byId;assert.equal(db.profile(id).equippedInstanceIds.primary,first);db.sell(id,'m416',1,1,second);assert.equal(db.inventoryQuantity(id,'red-dot'),2);assert.equal(db.reservedQuantity(id,'red-dot'),1);assert.equal(db.profile(id).instances.filter(r=>r.itemId==='m416').length,1);assert.throws(()=>db.sell(id,'m416',1,1,first),{code:'INSTANCE_EQUIPPED'});}finally{db?.close();rmSync(dir,{recursive:true,force:true});}});
test('raid extraction and retained death restore same host ID and fitting; lost host removes exact ID',()=>{for(const outcome of ['extracted','dead'])for(const retain of [true,false]){const {db,u}=fixture(':memory:',()=>retain?.9:.1);try{const id=db.profile(u.id).equippedInstanceIds.primary;db.equip(u.id,'primary:scope','red-dot',catalog);const [entry]=db.beginRaid('raid','room',[u.id]);const gear=Object.fromEntries(entry.gear.map(s=>[s.slot,s.itemId]));assert.equal(entry.gear.find(s=>s.slot==='primary').instanceId,id);const returned=entry.gear.map(s=>({itemId:s.itemId,quantity:1}));db.settleRaidPlayer('raid',u.id,outcome,returned,[],0,[],gear,1,gear);const profile=db.profile(u.id);if(outcome==='extracted'||retain){assert.equal(profile.equippedInstanceIds.primary,id);assert.equal(profile.instances.find(r=>r.id===id).fittings.scope,'red-dot');}else assert.equal(profile.instances.some(r=>r.id===id),false);assert.equal(profile.instances.filter(r=>r.itemId==='m416').length,db.inventoryQuantity(u.id,'m416'));}finally{db.close();}}});
test('armor modules stay with selected armor and fitted parts cannot be sold loose',()=>{const {db,u}=fixture();try{const part=ITEMS.find(i=>i.category==='attachment'&&i.slot==='vest');db.addInventory(u.id,part.id,1);const p=db.profile(u.id),first=p.equippedInstanceIds.armor,second=p.instances.find(r=>r.itemId==='armor-6'&&r.id!==first).id;db.equip(u.id,'armor:0',part.id,catalog,null,first);db.equip(u.id,'armor','armor-6',catalog,second);assert.equal(db.profile(u.id).equipped['armor:0'],undefined);assert.throws(()=>db.sell(u.id,part.id,1,1),{code:'ITEM_RESERVED'});db.equip(u.id,'armor','armor-6',catalog,first);assert.equal(db.profile(u.id).equipped['armor:0'],part.id);db.equip(u.id,'armor:0',null,catalog,null,first);db.sell(u.id,part.id,1,1);assert.equal(db.inventoryQuantity(u.id,part.id),0);}finally{db.close();}});

test('parts attached to a stored gun cannot also enter secure storage; detach transfers ownership back',()=>{const {db,u}=fixture();try{const id=u.id,first=db.profile(id).equippedInstanceIds.primary,second=db.profile(id).instances.find(r=>r.itemId==='m416'&&r.id!==first).id;db.equip(id,'primary:scope','red-dot',catalog,null,first);db.equip(id,'primary:scope','red-dot',catalog,null,second);db.equip(id,'primary',null,catalog);assert.equal(db.reservedQuantity(id,'red-dot'),2);const before=db.profile(id);assert.throws(()=>db.secure(id,'red-dot',1,catalog),{code:'INSUFFICIENT_ITEMS'});assert.deepEqual(db.profile(id),before);db.equip(id,'primary:scope',null,catalog,null,second);db.secure(id,'red-dot',1,catalog);assert.equal(db.profile(id).securePacked.find(s=>s.itemId==='red-dot').quantity,1);assert.equal(db.profile(id).instances.find(r=>r.id===first).fittings.scope,'red-dot');const [entry]=db.beginRaid('stored-parts','room',[id]);assert.equal(entry.secure.find(s=>s.itemId==='red-dot').quantity,1);assert.equal(db.inventoryQuantity(id,'red-dot'),1);assert.equal(db.instanceReserved(id,'red-dot'),1);}finally{db.close();}});

test('duplicate Mk14 bag returns consume each distinct fitting bundle once across old/new and retained death',()=>{
 for(const outcome of ['extracted','dead'])for(const prior of [0,1,2]){
  const db=new GameDatabase(':memory:',{lossRandom:()=>.9,bagLossChance:0});db.instanceCatalog=catalog.byId;
  try{
   const a='red-dot',b=ITEMS.find(i=>i.category==='attachment'&&i.slot==='scope'&&i.id!==a).id;
   const owned=prior?[{itemId:'mk14',quantity:prior},{itemId:a,quantity:1},...(prior===2?[{itemId:b,quantity:1}]:[])]:[];
   const gear=prior?{primary:'mk14','primary:scope':a,...(prior===2?{secondary:'mk14','secondary:scope':b}:{})}:{};
   const u=db.createUser('duplicate-bundles',Buffer.from('s'),Buffer.from('h'),owned,gear);const original=db.profile(u.id).equippedInstanceIds;
   db.beginRaid('duplicate-raid','room',[u.id]);
   const bag=[{itemId:'mk14',quantity:1,fittings:{scope:b}},{itemId:'mk14',quantity:1,fittings:{scope:a}}];
   db.settleRaidPlayer('duplicate-raid',u.id,outcome,[],bag,0,[],{},1,{});
   const p=db.profile(u.id),guns=p.instances.filter(r=>r.itemId==='mk14');assert.equal(guns.length,2);
   assert.deepEqual(guns.map(r=>r.fittings.scope).sort(),[a,b].sort(),'prior='+prior+' outcome='+outcome);
   for(const part of [a,b]){assert.equal(db.inventoryQuantity(u.id,part),1);assert.equal(db.instanceReserved(u.id,part),1);}
   if(prior)assert.equal(guns.find(r=>r.id===original.primary).fittings.scope,a);
   if(prior===2)assert.equal(guns.find(r=>r.id===original.secondary).fittings.scope,b);
   const before=p.instances;assert.equal(db.settleRaidPlayer('duplicate-raid',u.id,outcome,[],bag,0,[],{},2,{}).applied,false);assert.deepEqual(db.profile(u.id).instances,before);
  }finally{db.close();}
 }
});
test('stored armor with fittings requires confirmation and sells the fitted parts as one bundle',()=>{const {db,u}=fixture();try{const id=u.id,part=ITEMS.find(i=>i.category==='attachment'&&i.slot==='vest'),profile=db.profile(id),stashArmor=profile.instances.find(r=>r.itemId==='armor-6'&&r.status==='stash');db.addInventory(id,part.id,1);db.equip(id,'armor:0',part.id,catalog,null,stashArmor.id);assert.throws(()=>db.sell(id,'armor-6',1,0,stashArmor.id,{catalog,multiplier:0}),{code:'FITTINGS_CONFIRM_REQUIRED'});const before=db.getUserById(id).currency;db.sell(id,'armor-6',1,0,stashArmor.id,{includeFittings:true,catalog,multiplier:0});assert.equal(db.profile(id).instances.some(r=>r.id===stashArmor.id),false);assert.equal(db.inventoryQuantity(id,part.id),0);assert.equal(db.getUserById(id).currency,before+catalog.byId.get('armor-6').sell+part.sell);}finally{db.close();}});

