import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import type {SceneState} from '../src/contract';

test('actual Ford scene taxis, launches, relocates airborne, returns and recovers without duplicate baked jets',async({page})=>{
 test.setTimeout(180000);await page.setViewportSize({width:1600,height:1000});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.route('**/carrier-animation-fixture',r=>r.fulfill({contentType:'text/html',body:'<body style="margin:0"><canvas style="width:100vw;height:100vh;display:block"></canvas></body>'}));await page.goto('/carrier-animation-fixture');
 const report=await page.evaluate(async()=>{
  const p='/src/scene.ts',r='/src/rules.ts';const {createNavalScene}=await import(/* @vite-ignore */p),{createBattle}=await import(/* @vite-ignore */r);const w=createBattle(),carrier=w.ships.find((s:any)=>s.id==='0-carrier')!;carrier.x=14;carrier.z=14;let state:SceneState={you:0,turn:0,own:[carrier],revealed:[],islands:[],visibleCells:[],recon:[],selectedId:carrier.id,selectedCell:carrier};
  const scene=createNavalScene(document.querySelector('canvas')!,()=>{});scene.setState(state);for(let i=0;i<500&&!scene.diagnostics().texturesReady;i++)await new Promise(r=>setTimeout(r,30));let time=1;const tick=()=>scene.update(1/30,time+=1/30);scene.focus(carrier);for(let i=0;i<180;i++)tick();const images:Record<string,string>={},stages:Record<string,any>={};const capture=(name:string)=>{scene.render();images[name]=document.querySelector('canvas')!.toDataURL();stages[name]=scene.diagnostics();};capture('parked');
  state={...state,recon:[{team:0,carrierId:carrier.id,center:{x:14,z:12},expiresAt:9}]};scene.setState(state);const wanted=['taxiOut','lineup','catapult','climb','outbound','orbit'];for(let i=0;i<3600;i++){tick();const d=scene.diagnostics().carrierAircraft;for(const a of d.squadrons[0].actors)if(wanted.includes(a.phase)&&!stages[a.phase])capture(a.phase);if(d.squadrons[0].actors.every((a:any)=>a.phase==='orbit'))break;}
  const launched=scene.diagnostics().carrierAircraft;state={...state,recon:[{...state.recon[0],center:{x:16,z:13},expiresAt:11}]};scene.setState(state);tick();const redirected=scene.diagnostics().carrierAircraft;for(let i=0;i<600;i++)tick();capture('relocated');
  state={...state,recon:[]};scene.setState(state);tick();const recovery=['return','approach','landing','taxiIn'];for(let i=0;i<5400;i++){tick();const d=scene.diagnostics().carrierAircraft;for(const a of d.squadrons[0].actors)if(recovery.includes(a.phase)&&!stages[a.phase])capture(a.phase);if(d.squadrons[0].actors.every((a:any)=>a.phase==='parked'))break;}capture('recovered');
  const defaults=scene.getFleetAssets().carrier,aircraftParts=defaults.parts.filter((p:any)=>/^cv-aircraft-/.test(p.id));let bakedVertices=0;for(const sector of defaults.sectors){const part=sector.intact.getAttribute('aPart');for(let i=0;i<part.count;i++)if(aircraftParts.some((p:any)=>p.index===part.getX(i)))bakedVertices++;}
  scene.dispose();return{images,stages,launched,redirected,bakedVertices};
 });
 expect(errors).toEqual([]);expect(report.bakedVertices).toBe(0);expect(report.stages.parked.carrierAircraft.deckAircraft).toBe(4);expect(report.launched.airborneAircraft).toBe(4);expect(report.redirected.squadrons[0].actors.map((a:any)=>a.launches)).toEqual(report.launched.squadrons[0].actors.map((a:any)=>a.launches));expect(report.redirected.squadrons[0].actors.every((a:any)=>a.phase==='outbound')).toBe(true);
 for(const phase of ['taxiOut','lineup','catapult','climb','outbound','orbit','return','approach','landing','taxiIn'])expect(report.stages[phase]).toBeDefined();expect(report.stages.recovered.carrierAircraft.deckAircraft).toBe(4);expect(report.stages.recovered.carrierAircraft.squadrons[0].actors.every((a:any)=>a.phase==='parked'&&a.launches===1&&a.recoveries===1)).toBe(true);
 await mkdir('artifacts/carrier-animation',{recursive:true});for(const [phase,data] of Object.entries(report.images))await writeFile(`artifacts/carrier-animation/${phase}.png`,Buffer.from((data as string).split(',')[1]!, 'base64'));delete (report as any).images;await writeFile('artifacts/carrier-animation/scene-report.json',JSON.stringify(report,null,2));
});
