import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';

test('carrier breach clusters have one dominant and six small supported fires, proportional smoke and complete extinguishing',async({page},testInfo)=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.route('**/fire-fixture',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0}canvas{display:block;width:100vw;height:100vh}</style></head><body><canvas id="fire"></canvas></body></html>'}));await page.goto('/fire-fixture');
 const result=await page.evaluate(async()=>{
  const path='/src/scene.ts',{createNavalScene}=await import(/* @vite-ignore */path);const canvas=document.querySelector('canvas')!;const scene=createNavalScene(canvas,()=>{});for(let i=0;i<200&&!scene.diagnostics().texturesReady;i++)await new Promise(resolve=>setTimeout(resolve,50));if(!scene.diagnostics().texturesReady)throw new Error('Fleet material textures did not finish loading');let time=1;const tick=(dt=.05)=>{time+=dt;scene.update(dt,time);};
  const carrier={id:'fire-carrier',kind:'carrier',team:0,x:14,z:14,heading:0,hp:450,maxHp:1000,ap:4,maxAp:4,attacked:false,moved:false,sunk:false,damageMarks:[{x:-.25,z:-.45,seed:23},{x:.18,z:.04,seed:51},{x:-.18,z:.5,seed:102}]};const state={you:0,turn:0,own:[carrier],revealed:[],islands:[],visibleCells:[],recon:[]};
  const settle=async()=>{for(let i=0;i<600;i++){tick();await new Promise(r=>setTimeout(r,15));const p=scene.diagnostics().damagePreparation;if(p.pending===0&&p.queued.length===0)return;}throw new Error('Damage preparation did not settle');};scene.setState({...state,own:[{...carrier,hp:850}]});await settle();const light=scene.diagnostics();scene.setState(state);await settle();scene.focus(carrier);for(let i=0;i<90;i++)tick();
  const box=canvas.getBoundingClientRect();for(let i=0;i<14;i++){canvas.dispatchEvent(new WheelEvent('wheel',{deltaY:-120,clientX:box.width*.5,clientY:box.height*.5,bubbles:true,cancelable:true}));tick();}
  scene.render();const critical=scene.diagnostics(),firstImage=canvas.toDataURL();tick(.67);scene.render();const later=scene.diagnostics(),laterImage=canvas.toDataURL();
  scene.setState({...state,own:[{...carrier,damageControl:true}]});tick();scene.render();const extinguished=scene.diagnostics(),extinguishedImage=canvas.toDataURL();scene.dispose();return{light,critical,later,extinguished,firstImage,laterImage,extinguishedImage};
 });
 expect(errors).toEqual([]);expect(result.critical.fireBodies).toBe(21);expect(result.critical.fireDrawCalls).toBe(1);expect(result.critical.particles).toBeGreaterThan(200);expect(result.critical.particles).toBeLessThanOrEqual(1200);
 const fires=result.critical.fireEmitters;for(const id of new Set(fires.map((f:any)=>f.clusterId))){const group=fires.filter((f:any)=>f.clusterId===id),root=group.find((f:any)=>f.satellite===0);expect(group).toHaveLength(7);expect(group.every((f:any)=>f.satellite===0||f.flameHeight<root.flameHeight*.6)).toBe(true);expect(group.every((f:any)=>f.smokeHeight/f.flameHeight>6)).toBe(true);}expect(new Set(fires.map((f:any)=>f.seed)).size).toBe(21);expect(fires.every((f:any)=>f.rooted)).toBe(true);expect(fires[0].flameHeight).toBeGreaterThan(.05);expect(fires.every((f:any)=>f.flameHeight<1.4)).toBe(true);
 expect(result.later.fireEmitters.map((f:any)=>f.seed)).toEqual(fires.map((f:any)=>f.seed));expect(result.later.fireBodies).toBe(21);expect(result.firstImage).not.toBe(result.laterImage);expect(result.extinguished.fireBodies).toBe(0);expect(result.extinguished.particles).toBe(0);
 await mkdir('artifacts/fire',{recursive:true});for(const [name,data] of [['carrier-critical',result.firstImage],['carrier-critical-later',result.laterImage],['carrier-extinguished',result.extinguishedImage]])await writeFile(`artifacts/fire/${testInfo.project.name}-${name}.png`,Buffer.from(data.split(',')[1],'base64'));
 await writeFile(`artifacts/fire/${testInfo.project.name}-diagnostics.json`,JSON.stringify({critical:result.critical,later:result.later,extinguished:result.extinguished},null,2));
});


// An isolated volume fixture makes edge-on and overhead regressions measurable:
// every view must contain resolved hot pixels, even when an upright sheet would vanish.
test('breach volumes retain thickness from three angles and stay within the fire pool',async({page},testInfo)=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.route('**/volume-fixture',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><body style="margin:0"><canvas></canvas></body></html>'}));await page.goto('/volume-fixture');
 const result=await page.evaluate(async()=>{
  const threePath='/node_modules/three/build/three.module.js',effectsPath='/src/naval/effects.ts';const THREE=await import(/* @vite-ignore */threePath),{createEffects}=await import(/* @vite-ignore */effectsPath);const canvas=document.querySelector('canvas')!,renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setSize(640,480);const world=new THREE.Scene();world.background=new THREE.Color(0x30434a);const camera=new THREE.PerspectiveCamera(42,640/480,.01,100);const material=new THREE.MeshBasicMaterial({color:0x444b50});const effects=createEffects(world,camera,material,()=>480);const fires=[{cell:{x:0,z:0},strength:.95,y:0,position:new THREE.Vector3(-.62,0,0),scale:.32,flameScale:6,seed:23},{cell:{x:0,z:0},strength:.95,y:0,position:new THREE.Vector3(.62,0,0),scale:.32,flameScale:6,seed:51}];effects.setFires(fires);
  const copy=document.createElement('canvas');copy.width=640;copy.height=480;const context=copy.getContext('2d')!;const capture=()=>{renderer.render(world,camera);context.drawImage(canvas,0,0);const pixels=context.getImageData(0,0,640,480).data;let hotPixels=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]>125&&pixels[i]>pixels[i+1]*1.35&&pixels[i+1]>pixels[i+2]*1.3)hotPixels++;return{hotPixels,image:canvas.toDataURL(),calls:renderer.info.render.calls,triangles:renderer.info.render.triangles};};
  const views=[];for(const [name,position] of [['front',[0,1.0,3.4]],['side',[3.4,1.0,0]],['above',[0,3.4,.015]]] as const){camera.position.set(...position);camera.lookAt(0,.32,0);camera.updateMatrixWorld();effects.update(0,4.71);views.push({name,...capture()});}
  camera.position.set(0,1,3.4);camera.lookAt(0,.32,0);camera.updateMatrixWorld();effects.update(0,4.71);const unchangedA=capture();effects.update(0,4.71);const unchangedB=capture();effects.update(.5,5.21);const animated=capture();const active=effects.diagnostics();
  // Fence GPU timings with finish: this fixture measures only two small volumes,
  // not requestAnimationFrame pacing or unrelated scene startup compilation.
  const gl=renderer.getContext();const measure=(burning:boolean)=>{effects.setFires(burning?fires:[]);effects.update(0,5.21);for(let i=0;i<4;i++)renderer.render(world,camera);gl.finish();const start=performance.now();for(let i=0;i<24;i++){effects.update(1/60,5.21+i/60);renderer.render(world,camera);}gl.finish();return(performance.now()-start)/24;};const emptyMs=measure(false),fireMs=measure(true);
  effects.setFires(Array.from({length:420},(_,i)=>({...fires[i%2],position:new THREE.Vector3(i%10,0,Math.floor(i/10)),seed:i+1})));effects.update(0,6);const stress=effects.diagnostics();effects.clear();effects.update(0,6);const cleared=effects.diagnostics();effects.dispose();material.dispose();renderer.dispose();return{views,active,stress,cleared,stable:unchangedA.image===unchangedB.image,animated:unchangedB.image!==animated.image,emptyMs,fireMs};
 });
 expect(errors).toEqual([]);expect(result.stable).toBe(true);expect(result.animated).toBe(true);expect(result.active.fireTechnique).toBe('bounded-volume-emission-absorption');expect(result.active.fireNoiseBytes).toBe(32768);expect(result.active.fireEmitters.every((f:any)=>f.volumeDepth>.35)).toBe(true);for(const view of result.views){expect(view.hotPixels,view.name).toBeGreaterThan(80);expect(view.calls).toBeLessThanOrEqual(2);expect(view.triangles).toBe(24);}expect(result.stress.fireBodies).toBe(392);expect(result.stress.particles).toBeLessThanOrEqual(1200);expect(result.cleared.fireBodies).toBe(0);expect(result.cleared.particles).toBe(0);
 await mkdir('artifacts/fire',{recursive:true});for(const view of result.views)await writeFile(`artifacts/fire/${testInfo.project.name}-volume-${view.name}.png`,Buffer.from(view.image.split(',')[1],'base64'));await writeFile(`artifacts/fire/${testInfo.project.name}-volume-diagnostics.json`,JSON.stringify({...result,views:result.views.map(({image,...view})=>view)},null,2));
});
