import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
async function ready(page:import('@playwright/test').Page){
 await page.waitForFunction(()=>{const h=window.__THREE_GAME_TEST_HOOKS__!.getState(),p=h.damagePreparation as {status:string;pending:number;queued:unknown[]};return h.texturesReady&&!h.presentationBusy&&p.status==='ready'&&!p.pending&&!p.queued.length;},{},{timeout:60000});
}
test('reverse reservations execute all seven ships in fleet order, one visible attack at a time',async({page})=>{
 test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.waitForFunction(()=>!!window.__THREE_GAME_TEST_HOOKS__);
 await page.evaluate(()=>{const h=window.__THREE_GAME_TEST_HOOKS__!;h.setState('airstrike');const w=h.getState().world!;w.islands=[];w.recon=[];w.sonar=[];
  for(const s of w.ships.filter(s=>s.team===0)){s.sunk=true;s.hp=0;}h.refresh();
  w.ships.filter(s=>s.team===0).forEach((s,i)=>Object.assign(s,{sunk:false,hp:s.maxHp,ap:4,scouted:false,attacked:false,x:14+i,z:15}));h.refresh();
 });await ready(page);
 const reserved=await page.evaluate(()=>{const h=window.__THREE_GAME_TEST_HOOKS__!;for(const id of ['0-battleship-3','0-battleship-2','0-battleship-1','0-destroyer-3','0-destroyer-2','0-destroyer-1'])h.command({type:'attack',shipId:id,target:{x:18,z:18}});h.command({type:'recon',shipId:'0-carrier',target:{x:18,z:18}});return h.getState().state;});
 expect(reserved.queuedAttacks).toHaveLength(7);expect(reserved.lastShot).toBeUndefined();
 await page.evaluate(()=>{const win=window as unknown as {combatAudit:{samples:unknown[];timer:number}};win.combatAudit={samples:[],timer:0};win.combatAudit.timer=window.setInterval(()=>{const d=window.__THREE_GAME_TEST_HOOKS__!.getState() as any;win.combatAudit.samples.push({time:performance.now(),phase:d.state.combatPhase,turn:d.state.turn,shot:d.state.lastShot,projectiles:d.projectiles,cameraStage:d.combatCameraStage,busy:d.presentationBusy,renderer:d.renderer});},80);window.__THREE_GAME_TEST_HOOKS__!.command({type:'end'});});
 await page.waitForFunction(()=>{const d=window.__THREE_GAME_TEST_HOOKS__!.getState();return d.state.turn===1&&d.state.combatPhase==='action';},{},{timeout:180000});
 const report=await page.evaluate(()=>{const win=window as unknown as {combatAudit:{samples:any[];timer:number}};clearInterval(win.combatAudit.timer);const seen=new Map<number,any>();for(const d of win.combatAudit.samples)if(d.shot?.by===0&&!seen.has(d.shot.sequence))seen.set(d.shot.sequence,d);return {samples:win.combatAudit.samples,order:[...seen.values()].map(d=>d.shot.sourceShip.id),diagnostics:window.__THREE_GAME_TEST_HOOKS__!.getState() as any};});
 expect(report.order).toEqual(['0-carrier','0-destroyer-1','0-destroyer-2','0-destroyer-3','0-battleship-1','0-battleship-2','0-battleship-3']);
 expect(Math.max(...report.samples.map(d=>d.projectiles.length))).toBe(1);expect(report.diagnostics.missileLaunches).toBe(3);expect(report.diagnostics.gunLaunches).toBe(3);
 for(let seq=1;seq<=7;seq++){expect(report.samples.some(d=>d.shot?.sequence===seq&&d.projectiles.some((p:any)=>p.sequence===seq&&p.phase==='flight'))).toBe(true);expect(report.samples.some(d=>d.shot?.sequence===seq&&d.cameraStage==='impact')).toBe(true);}
 expect(errors).toEqual([]);await fs.mkdir('artifacts/queued-combat-browser',{recursive:true});await fs.writeFile('artifacts/queued-combat-browser/fleet-order.json',JSON.stringify({errors,...report},null,2));await page.screenshot({path:'artifacts/queued-combat-browser/fleet-complete.png'});
});
test('unseen enemy launches from its actual model and follows missile defense and shell impact',async({page})=>{
 test.setTimeout(160000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.waitForFunction(()=>!!window.__THREE_GAME_TEST_HOOKS__);
 await page.evaluate(()=>{const h=window.__THREE_GAME_TEST_HOOKS__!;h.setState('airstrike');const w=h.getState().world!;w.islands=[];w.recon=[];w.sonar=[];w.turn=1;w.turnNumber=4;w.round=2;
  // Both launchers are outside basic sight; the current firing ship alone is a cinematic actor.
  Object.assign(w.ships.find(s=>s.id==='1-carrier')!,{x:15,z:3});Object.assign(w.ships.find(s=>s.id==='1-destroyer-1')!,{x:15,z:4});Object.assign(w.ships.find(s=>s.id==='1-battleship-1')!,{x:15,z:5});h.refresh();h.seed(1);
 });await ready(page);
 await page.evaluate(async()=>{const h=window.__THREE_GAME_TEST_HOOKS__!,w=h.getState().world!;const {applyAction}=await import('../src/rules');for(const id of ['1-battleship-1','1-destroyer-1']){const r=applyAction(w,1,{type:'attack',shipId:id,target:{x:3,z:3}});if(!r.ok)throw new Error(r.error);}applyAction(w,1,{type:'recon',shipId:'1-carrier',target:{x:3,z:3}});applyAction(w,1,{type:'end'});const win=window as unknown as {enemyCombatAudit:{samples:any[];timer:number}};win.enemyCombatAudit={samples:[],timer:0};win.enemyCombatAudit.timer=window.setInterval(()=>{const d=h.getState() as any;win.enemyCombatAudit.samples.push({time:performance.now(),shot:d.state.lastShot,phase:d.state.combatPhase,projectiles:d.projectiles,cameraStage:d.combatCameraStage,sourceId:d.cinematicSourceId,visible:d.visibleShips,revealed:d.state.revealed.map((s:any)=>s.id),missileLaunches:d.missileLaunches,gunLaunches:d.gunLaunches,ciws:d.ciwsTracers,intercept:d.interceptSmokeCount,camera:d.camera,aircraft:d.carrierAircraft});},80);h.refresh();});
 await page.waitForFunction(()=>{const d=window.__THREE_GAME_TEST_HOOKS__!.getState();return d.state.turn===0&&d.state.combatPhase==='action'&&!d.presentationBusy;},{},{timeout:100000});
 const report=await page.evaluate(()=>{const win=window as unknown as {enemyCombatAudit:{samples:any[];timer:number}};clearInterval(win.enemyCombatAudit.timer);return {samples:win.enemyCombatAudit.samples,final:window.__THREE_GAME_TEST_HOOKS__!.getState() as any};});
 for(const [id,kind]of [['1-destroyer-1','missile'],['1-battleship-1','shell']]){const flight=report.samples.find(d=>d.shot?.kind===kind&&d.projectiles.some((p:any)=>p.phase==='flight'));expect(flight).toBeTruthy();expect(flight.sourceId).toBe(id);expect(flight.visible).toContain(id);expect(flight.revealed).not.toContain(id);expect(flight.cameraStage).toBe('launch');const p=flight.projectiles[0],s=flight.shot.source;expect(Math.hypot(p.source[0]-((s.x+.5)*4-60),p.source[2]-((s.z+.5)*4-60))).toBeLessThan(2);expect(report.samples.some(d=>d.shot?.kind===kind&&d.cameraStage==='impact')).toBe(true);}
 const air=report.samples.find(d=>d.shot?.kind==='airstrike'&&d.projectiles.some((p:any)=>p.phase==='flight'));expect(air).toBeTruthy();expect(air.sourceId).toBe('1-carrier');expect(air.cameraStage).toBe('launch');expect(air.aircraft.squadrons.some((s:any)=>s.carrierId==='1-carrier'&&s.actors.some((a:any)=>['outbound','orbit'].includes(a.phase)))).toBe(true);expect(air.revealed).not.toContain('1-carrier');expect(report.final.cinematicSourceId).toBeNull();expect(report.final.visibleShips).not.toContain('1-destroyer-1');expect(report.final.visibleShips).not.toContain('1-battleship-1');expect(report.final.missileLaunches).toBe(1);expect(report.final.gunLaunches).toBe(1);expect(report.samples.some(d=>d.ciws>0)).toBe(true);expect(errors).toEqual([]);
 await fs.mkdir('artifacts/queued-combat-browser',{recursive:true});await fs.writeFile('artifacts/queued-combat-browser/enemy-camera.json',JSON.stringify({errors,...report},null,2));
});

