import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';

test('missile trail, interception and water spray stay bounded and follow impact phases',async({page},testInfo)=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.route('**/fire-fixture',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0}canvas{display:block;width:100vw;height:100vh}</style></head><body><canvas id="fire"></canvas></body></html>'}));await page.goto('/fire-fixture');
 const result=await page.evaluate(async()=>{
  const path='/src/scene.ts',{createNavalScene}=await import(/* @vite-ignore */path);const canvas=document.querySelector('canvas')!;const scene=createNavalScene(canvas,()=>{});for(let i=0;i<200&&!scene.diagnostics().texturesReady;i++)await new Promise(resolve=>setTimeout(resolve,50));if(!scene.diagnostics().texturesReady)throw new Error('Fleet material textures did not finish loading');await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));let time=1;const tick=(dt=.05)=>{time+=dt;scene.update(dt,time);};
  const carrier={id:'fire-carrier',kind:'carrier',team:0,x:14,z:14,heading:0,hp:140,maxHp:1000,ap:4,maxAp:4,attacked:false,moved:false,sunk:false,damageMarks:[{x:-.25,z:-.45,seed:23},{x:.18,z:.04,seed:51},{x:-.18,z:.5,seed:102}]};const state={you:0,turn:0,own:[carrier],revealed:[],islands:[],visibleCells:[],recon:[]};
  const source={...carrier,id:'launcher',kind:'destroyer',hp:600,maxHp:600,damageMarks:[],x:14,z:14};scene.setState({...state,own:[source]});scene.focus(source);for(let i=0;i<90;i++)tick();const box=canvas.getBoundingClientRect();for(let i=0;i<7;i++){canvas.dispatchEvent(new WheelEvent('wheel',{deltaY:-120,clientX:box.width*.5,clientY:box.height*.5,bubbles:true,cancelable:true}));tick();}
  scene.impact({x:15,z:14,sequence:101,by:0,hit:false,damage:0,blocked:false,halved:false,kind:'missile',source:{x:14,z:14}});for(let i=0;i<12;i++)tick();scene.render();const trail=scene.diagnostics(),trailImage=canvas.toDataURL();for(let i=0;i<17;i++)tick();scene.render();const splash=scene.diagnostics(),splashImage=canvas.toDataURL();scene.clearEffects();scene.impact({x:15,z:14,sequence:102,by:0,hit:false,damage:0,blocked:true,halved:false,kind:'missile',source:{x:14,z:14}});for(let i=0;i<20;i++)tick();scene.render();const intercepted=scene.diagnostics(),interceptImage=canvas.toDataURL();for(let i=0;i<100;i++)tick();scene.clearEffects();tick();const cleared=scene.diagnostics();scene.dispose();return{trail,splash,intercepted,cleared,trailImage,splashImage,interceptImage};
 });
 expect(errors).toEqual([]);expect(result.trail.projectiles).toHaveLength(1);expect(result.trail.projectiles[0].trailPoints).toBeGreaterThan(10);expect(result.trail.projectiles[0].trailPoints).toBeLessThanOrEqual(44);expect(result.splash.projectiles).toEqual([]);expect(result.splash.waterRings).toBeGreaterThan(0);expect(result.intercepted.airbursts).toBe(1);expect(result.intercepted.waterRings).toBe(0);for(const d of [result.trail,result.splash,result.intercepted])expect(d.particles).toBeLessThanOrEqual(1200);expect(result.cleared.particles).toBe(0);
 await mkdir('artifacts/vfx',{recursive:true});for(const [name,data] of [['missile-trail',result.trailImage],['water-impact',result.splashImage],['air-intercept',result.interceptImage]])await writeFile(`artifacts/vfx/${testInfo.project.name}-${name}.png`,Buffer.from(data.split(',')[1],'base64'));await writeFile(`artifacts/vfx/${testInfo.project.name}-diagnostics.json`,JSON.stringify({trail:result.trail,splash:result.splash,intercepted:result.intercepted},null,2));
});
