import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import type {ShipView,ShipKind} from './contract';
import {buildFleetAssets,configureFleetMaterial,fleetGeometry,fleetDetachedGeometry,type DamageMark,type FleetAsset} from './naval/fleet';
import {loadFleetSourceTextures} from './naval/source-material';
import {damageFireOrigin} from './naval/fire-origin';
import {activeFireMarks} from './naval/fire-state';
import {createEffects} from './naval/effects';
import {installSpatialRaycast} from './naval/spatial-raycast';
import {guardNavalCamera} from './naval/camera';
import {installModelNavigation,frameNavalBounds} from './naval/navigation';
export function createEnemyPreview(canvas:HTMLCanvasElement,sharedAssets?:Record<ShipKind,FleetAsset>,sharedGeometry?:(ship:ShipView,low:boolean)=>THREE.BufferGeometry){
 const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.setClearColor(0x061017,0);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.025,40),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.enablePan=true;controls.screenSpacePanning=true;controls.zoomToCursor=true;controls.panSpeed=1.5;controls.zoomSpeed=1.15;controls.mouseButtons.RIGHT=THREE.MOUSE.PAN;controls.minDistance=0;controls.maxDistance=Infinity;controls.minPolarAngle=.01;controls.maxPolarAngle=Math.PI-.01;controls.target.set(0,.25,0);camera.position.set(2.6,2.1,3.8);controls.update();
 const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.05);scene.environment=env.texture;scene.environmentIntensity=.68;room.dispose();pmrem.dispose();scene.add(new THREE.HemisphereLight(0xc3e7f3,0x183c44,1.1));const key=new THREE.DirectionalLight(0xffdfb6,2.5);key.position.set(-3,6,-4);scene.add(key);const rim=new THREE.DirectionalLight(0x83c1f1,1.15);rim.position.set(3,2,4);scene.add(rim);
 const loader=new THREE.TextureLoader(),base=import.meta.env.BASE_URL,color=loader.load(`${base}materials/naval-v2-color.webp`),normal=loader.load(`${base}materials/naval-v2-normal.webp`),rough=loader.load(`${base}materials/naval-v2-roughness.webp`);color.colorSpace=THREE.SRGBColorSpace;const material=new THREE.MeshStandardMaterial({vertexColors:true,map:color,normalMap:normal,roughnessMap:rough,normalScale:new THREE.Vector2(.23,.23),roughness:.68,metalness:.35,side:THREE.DoubleSide});const anisotropy=renderer.capabilities.getMaxAnisotropy(),sourceTextures=loadFleetSourceTextures(loader,base,anisotropy),sourceMaps=Object.values(sourceTextures).flatMap(t=>[t.color,t.pbr,t.normal]);for(const texture of [color,normal,rough])texture.anisotropy=anisotropy;configureFleetMaterial(material,sourceTextures);
 const assets=sharedAssets??buildFleetAssets(),group=new THREE.Group();scene.add(group);const effects=createEffects(scene,camera,material,()=>Math.max(1,canvas.clientHeight));let ship:ShipView|undefined,mesh:THREE.Mesh|undefined,signature='',marks:DamageMark[]=[],points:ReturnType<typeof damageFireOrigin>[]=[];
 const cameraGuard=guardNavalCamera(camera,controls,()=>mesh?[mesh]:[],{sea:-Infinity,surfaceClearance:false});
 const navigation=installModelNavigation(camera,controls,canvas,.65,(origin,direction)=>{if(!mesh)return;mesh.updateWorldMatrix(true,true);return new THREE.Raycaster(origin,direction).intersectObject(mesh,false)[0]?.distance;},{center:new THREE.Vector3(0,.25,0),maxDistance:()=>Math.max(1.5,(ship?assets[ship.kind].fittedSize[2]:3.6)*3)});
 function resize(){const r=canvas.getBoundingClientRect();if(r.width<1||r.height<1)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}
 function setShip(next:ShipView|undefined){if(!next){ship=undefined;signature='';marks=[];points=[];if(mesh){mesh.geometry.dispose();group.remove(mesh);mesh=undefined;}effects.clear();renderer.clear();return;}const prior=ship,changedKind=ship?.kind!==next.kind;const m=next.damageMarks?.length?next.damageMarks:next.hp<next.maxHp?[{x:.12,z:-.12,seed:91}]:[],sig=`${next.id}:${next.kind}:${next.hp}:${JSON.stringify([m,next.parts])}`;ship={...next,damageMarks:m.map(p=>({...p}))};group.rotation.y=next.heading+Math.PI;if(sig!==signature){if(prior?.id===next.id){group.updateMatrixWorld(true);effects.detach(fleetDetachedGeometry(assets[next.kind],prior.damageMarks??[],m,prior.parts,next.parts),group.matrixWorld,m.at(-1)?.seed??1);}if(mesh){mesh.geometry.dispose();group.remove(mesh);}mesh=new THREE.Mesh(sharedGeometry?.({...next,damageMarks:m},false)??fleetGeometry(assets[next.kind],m,false,next.parts),material);installSpatialRaycast(mesh);group.add(mesh);signature=sig;marks=m;if(changedKind){resize();navigation.stop();group.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(group),pose=frameNavalBounds(camera,box,new THREE.Vector3(.8,.6,1.2),1.12);controls.target.copy(pose.target);camera.position.copy(pose.position);camera.lookAt(pose.target);cameraGuard.rebase();controls.update();}}points=activeFireMarks(ship,m).slice(-4).map(mark=>damageFireOrigin(assets[next.kind],mark,mesh!.geometry)).filter(origin=>origin.verified);resize();}
 function update(dt:number,t:number){if(!ship||!mesh)return;navigation.update(dt);controls.update();cameraGuard.update();group.updateMatrixWorld(true);const damage=1-ship.hp/ship.maxHp;effects.setFires(ship.damageControl?[]:points.map(origin=>{const at=group.localToWorld(origin.position.clone());return{cell:ship!,position:at,y:at.y,opening:origin.opening,originVerified:true,strength:.65+damage*.25,scale:.065+damage*.022};}));effects.update(Math.min(.05,dt),t);camera.far=Math.max(40,camera.position.length()+40);camera.updateProjectionMatrix();renderer.render(scene,camera);}
 function diagnostics(){return{visible:!!ship,shipId:ship?.id,hp:ship?.hp,damageMarks:marks.length,activeFireMarks:ship?activeFireMarks(ship,marks):[],modelScale:group.scale.toArray(),camera:{position:camera.position.toArray(),target:controls.target.toArray(),distance:camera.position.distanceTo(controls.target),minDistance:controls.minDistance,maxDistance:controls.maxDistance,...cameraGuard.diagnostics(),...navigation.diagnostics()},renderer:{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures},...effects.diagnostics()};}
 function dispose(){setShip(undefined);navigation.dispose();cameraGuard.dispose();controls.dispose();effects.dispose();if(!sharedAssets)for(const a of Object.values(assets))for(const s of a.sectors)for(const g of [s.intact,s.low,s.wreck,s.fragment])g.dispose();material.dispose();color.dispose();normal.dispose();rough.dispose();sourceMaps.forEach(t=>t.dispose());env.dispose();renderer.dispose();renderer.forceContextLoss();}
 resize();return{setShip,update,resize,dispose,diagnostics};
}
