import * as THREE from 'three';
import type {OrbitControls} from 'three/addons/controls/OrbitControls.js';
/** Sweep every control change, including synchronous wheel updates, from the last valid pose. */
export function guardNavalCamera(camera:THREE.PerspectiveCamera,controls:OrbitControls,obstacles:()=>THREE.Object3D[],options:{sea?:number;seaAt?:(x:number,z:number)=>number;radius?:number;surfaceClearance?:boolean;horizontalPanActive?:()=>boolean}={}){
 const safePosition=camera.position.clone(),safeTarget=controls.target.clone(),ray=new THREE.Raycaster(),radius=options.radius??.22;
 const seaLevel=()=>options.seaAt?.(camera.position.x,camera.position.z)??options.sea??.46;
 let resolving=false,collisions=0,lastObstacle='none',detailedRaycasts=0,broadPhaseRejected=0;
 const localGroupBounds=new WeakMap<THREE.Object3D,THREE.Box3>(),worldBounds=new WeakMap<THREE.Object3D,THREE.Box3>(),probePoint=new THREE.Vector3();
 function boundsFor(object:THREE.Object3D){let local:THREE.Box3;if(object instanceof THREE.Mesh){if(!object.geometry.boundingBox)object.geometry.computeBoundingBox();local=object.geometry.boundingBox!;}else{let cached=localGroupBounds.get(object);if(!cached){cached=new THREE.Box3().setFromObject(object).applyMatrix4(object.matrixWorld.clone().invert());localGroupBounds.set(object,cached);}local=cached;}let world=worldBounds.get(object);if(!world){world=new THREE.Box3();worldBounds.set(object,world);}world.copy(local).applyMatrix4(object.matrixWorld).expandByScalar(radius);return world;}
 function candidates(meshes:THREE.Object3D[]){return meshes.filter(mesh=>{const box=worldBounds.get(mesh)!;const eligible=box.containsPoint(ray.ray.origin)||!!ray.ray.intersectBox(box,probePoint)&&probePoint.distanceToSquared(ray.ray.origin)<=ray.far*ray.far;if(eligible)detailedRaycasts++;else broadPhaseRejected++;return eligible;});}
 const offsets=[new THREE.Vector3(),new THREE.Vector3(radius,0,0),new THREE.Vector3(-radius,0,0),new THREE.Vector3(0,radius,0),new THREE.Vector3(0,-radius,0),new THREE.Vector3(0,0,radius),new THREE.Vector3(0,0,-radius)];
 function update(){if(resolving)return;resolving=true;
  const horizontal=options.horizontalPanActive?.()??false,sea=seaLevel(),desired=camera.position.clone(),target=controls.target.clone();if(horizontal){desired.y=safePosition.y;target.y=safeTarget.y;camera.position.y=desired.y;controls.target.y=target.y;if(desired.y<sea){camera.position.copy(safePosition);controls.target.copy(safeTarget);collisions++;lastObstacle='horizontal-sea';resolving=false;return;}}if(desired.y<sea){const lift=sea-desired.y;desired.y+=lift;target.y+=lift;camera.position.copy(desired);controls.target.copy(target);collisions++;lastObstacle='sea-slide';}const delta=desired.clone().sub(safePosition),length=delta.length();let fraction=1;const meshes=obstacles();meshes.forEach(o=>{o.updateWorldMatrix(true,true);boundsFor(o);});
  let contactNormal:THREE.Vector3|undefined;
  const sweep=(start:THREE.Vector3,move:THREE.Vector3)=>{const len=move.length();let f=1,normal:THREE.Vector3|undefined;if(len<1e-7)return{f,normal};const direction=move.clone().divideScalar(len);ray.near=0;ray.far=len+radius;for(const offset of offsets){ray.set(start.clone().add(offset),direction);for(const hit of ray.intersectObjects(candidates(meshes),true)){if(!hit.face)continue;const matrix=hit.object.matrixWorld.clone();if(hit.object instanceof THREE.InstancedMesh&&hit.instanceId!==undefined){const instance=new THREE.Matrix4();hit.object.getMatrixAt(hit.instanceId,instance);matrix.multiply(instance);}const n=hit.face.normal.clone().applyNormalMatrix(new THREE.Matrix3().getNormalMatrix(matrix));if(n.dot(direction)>=-1e-5)continue;const candidate=Math.max(0,(hit.distance-(offset.lengthSq()===0?radius:0))/len);if(candidate<f){f=candidate;normal=n;lastObstacle=hit.object.name||'visible-mesh';}break;}}return{f,normal};};
  if(length>1e-6){const hit=sweep(safePosition,delta);fraction=hit.f;contactNormal=hit.normal;}
  if(fraction<1){collisions++;camera.position.copy(safePosition).lerp(desired,fraction);controls.target.copy(safeTarget).lerp(target,fraction);let remainder=delta.clone().multiplyScalar(1-fraction);for(let attempt=0;attempt<2&&contactNormal;attempt++){if(horizontal){contactNormal=contactNormal.clone().setY(0).normalize();remainder.y=0;}remainder.addScaledVector(contactNormal,-Math.min(0,remainder.dot(contactNormal)));const hit=sweep(camera.position,remainder),step=remainder.clone().multiplyScalar(hit.f);camera.position.add(step);controls.target.add(step);if(hit.f>=1)break;remainder.multiplyScalar(1-hit.f);contactNormal=hit.normal;}}
  // Recover newly moved/spawned geometry around a stationary camera as well.
  if(options.surfaceClearance!==false&&camera.position.y<14){ray.set(camera.position.clone().add(new THREE.Vector3(0,radius,0)),new THREE.Vector3(0,-1,0));ray.near=0;ray.far=radius*2;const hit=ray.intersectObjects(candidates(meshes),true)[0];const floor=Math.max(sea,hit?hit.point.y+radius:sea);if(camera.position.y<floor){if(horizontal){camera.position.copy(safePosition);controls.target.copy(safeTarget);collisions++;lastObstacle='horizontal-obstacle';resolving=false;return;}const lift=floor-camera.position.y;camera.position.y+=lift;controls.target.y+=lift;collisions++;lastObstacle=hit?'surface-clearance':'sea';}}
  // A slide against sloped geometry may lower the probe after the first sea test.
  const finalSea=seaLevel();if(horizontal){camera.position.y=safePosition.y;controls.target.y=safeTarget.y;if(camera.position.y<finalSea){camera.position.copy(safePosition);controls.target.copy(safeTarget);resolving=false;return;}}if(camera.position.y<finalSea){const lift=finalSea-camera.position.y;camera.position.y+=lift;controls.target.y+=lift;}
  // Preserve a coherent orbit vector after clipping; do not clamp camera Y alone.
  let offset=camera.position.clone().sub(controls.target),distance=offset.length();if(distance<1e-5){offset.set(0,1,1);distance=offset.length();}const bounded=THREE.MathUtils.clamp(distance,controls.minDistance,controls.maxDistance);if(Math.abs(distance-bounded)>1e-5)controls.target.copy(camera.position).addScaledVector(offset,-bounded/distance);
  camera.lookAt(controls.target);camera.updateMatrixWorld();safePosition.copy(camera.position);safeTarget.copy(controls.target);resolving=false;
 }
 controls.addEventListener('change',update);
 return{update,rebase(){safePosition.copy(camera.position);safeTarget.copy(controls.target);},diagnostics:()=>({collisions,lastObstacle,detailedRaycasts,broadPhaseRejected,seaClearance:Number.isFinite(seaLevel())?camera.position.y-seaLevel():null,sweepRadius:radius}),dispose(){controls.removeEventListener('change',update);}};
}


