import * as THREE from 'three';
export interface HullChunk {geometry:THREE.BufferGeometry;lowGeometry:THREE.BufferGeometry;center:THREE.Vector3;side:number;cutEdges:number;interiorVertices:number}
type Vertex={p:THREE.Vector3;n:THREE.Vector3;c:THREE.Vector3;uv:THREE.Vector2;interior:number;part:number;surface:number;sourceTile:number};
/** Split the existing damaged source surface. The open cross-section retains authored rooms/ribs.
 * Only actual triangle/plane intersections acquire a narrow exposed-metal thickness strip. */
export function fractureHull(source:THREE.BufferGeometry,impactZ:number,seed=1):HullChunk[]{
 const g=source.index?source.toNonIndexed():source,p=g.getAttribute('position'),n=g.getAttribute('normal'),c=g.getAttribute('color'),uv=g.getAttribute('uv'),interior=g.getAttribute('aInterior'),part=g.getAttribute('aPart'),surface=g.getAttribute('aSurface'),sourceTile=g.getAttribute('aSourceTile');g.computeBoundingBox();const box=g.boundingBox!,length=box.max.z-box.min.z,cut=THREE.MathUtils.clamp(impactZ,box.min.z+length*.28,box.max.z-length*.28),tilt=.12+Math.sin(seed)*.07;
 const distance=(v:Vertex)=>v.p.z-cut+v.p.x*tilt+v.p.y*.08;
 const read=(i:number):Vertex=>({p:new THREE.Vector3().fromBufferAttribute(p,i),n:new THREE.Vector3().fromBufferAttribute(n,i),c:c?new THREE.Vector3().fromBufferAttribute(c,i):new THREE.Vector3(.3,.3,.3),uv:uv?new THREE.Vector2(uv.getX(i),uv.getY(i)):new THREE.Vector2(),interior:interior?.getX(i)??0,part:part?.getX(i)??-1,surface:surface?.getX(i)??0,sourceTile:sourceTile?.getX(i)??-1});
 const mix=(a:Vertex,b:Vertex,t:number):Vertex=>({p:a.p.clone().lerp(b.p,t),n:a.n.clone().lerp(b.n,t).normalize(),c:a.c.clone().lerp(b.c,t),uv:a.uv.clone().lerp(b.uv,t),interior:Math.min(a.interior,b.interior),part:a.part,surface:a.surface,sourceTile:a.sourceTile});
 const buckets:[Vertex[],Vertex[]]=[[],[]],edgeCounts=[0,0];
 for(let i=0;i<p.count;i+=3){const tri=[read(i),read(i+1),read(i+2)];for(let side=0;side<2;side++){const sign=side?1:-1,poly:Vertex[]=[],cross:Vertex[]=[];for(let j=0;j<3;j++){const a=tri[j],b=tri[(j+1)%3],da=distance(a)*sign,db=distance(b)*sign;if(da>=0)poly.push(a);if((da>=0)!==(db>=0)){const v=mix(a,b,da/(da-db));poly.push(v);cross.push(v);}}for(let j=1;j+1<poly.length;j++)buckets[side].push(poly[0],poly[j],poly[j+1]);
  if(cross.length===2&&cross[0].p.distanceToSquared(cross[1].p)>1e-9){const a=cross[0],b=cross[1],thickness=.007+(a.interior>.5?.005:0),offset=a.n.clone().add(b.n).normalize().multiplyScalar(-thickness),normal=new THREE.Vector3(tilt,.08,1).normalize().multiplyScalar(-sign),metal=new THREE.Vector3(.15,.135,.12);const edge=(v:Vertex,back:boolean):Vertex=>({...v,p:v.p.clone().add(back?offset:new THREE.Vector3()),n:normal,c:metal,interior:1,sourceTile:-1});const aa=edge(a,false),bb=edge(b,false),cc=edge(b,true),dd=edge(a,true);buckets[side].push(aa,bb,cc,aa,cc,dd);edgeCounts[side]++;}
 }}
 if(source.index)g.dispose();return buckets.map((vertices,i)=>{const bounds=new THREE.Box3().setFromPoints(vertices.map(v=>v.p)),center=bounds.getCenter(new THREE.Vector3()),pos:number[]=[],norm:number[]=[],colors:number[]=[],uvs:number[]=[],inside:number[]=[],parts:number[]=[],surfaces:number[]=[],sourceTiles:number[]=[];for(const v of vertices){pos.push(v.p.x-center.x,v.p.y-center.y,v.p.z-center.z);norm.push(v.n.x,v.n.y,v.n.z);colors.push(v.c.x,v.c.y,v.c.z);uvs.push(v.uv.x,v.uv.y);inside.push(v.interior);parts.push(v.part);surfaces.push(v.surface);sourceTiles.push(v.sourceTile);}const geometry=new THREE.BufferGeometry();for(const [name,array,size] of [['position',pos,3],['normal',norm,3],['color',colors,3],['uv',uvs,2],['aInterior',inside,1],['aPart',parts,1],['aSurface',surfaces,1],['aSourceTile',sourceTiles,1]] as [string,number[],number][])geometry.setAttribute(name,new THREE.Float32BufferAttribute(array,size));geometry.computeBoundingSphere();geometry.computeBoundingBox();const keep:number[]=[];for(let j=0;j<vertices.length;j+=3){const a=vertices[j],b=vertices[j+1],c=vertices[j+2],area=b.p.clone().sub(a.p).cross(c.p.clone().sub(a.p)).length()*.5;if(a.interior>.5||area>.00015||Math.abs(distance(a))<.025)keep.push(j,j+1,j+2);}const lowGeometry=new THREE.BufferGeometry();for(const name of Object.keys(geometry.attributes)){const attr=geometry.getAttribute(name),data:number[]=[];for(const index of keep)for(let component=0;component<attr.itemSize;component++)data.push(attr.array[index*attr.itemSize+component]);lowGeometry.setAttribute(name,new THREE.Float32BufferAttribute(data,attr.itemSize));}lowGeometry.computeBoundingSphere();lowGeometry.computeBoundingBox();return{geometry,lowGeometry,center,side:i?1:-1,cutEdges:edgeCounts[i],interiorVertices:inside.filter(v=>v>.5).length};});
}
