import {supportsWeaponAttachment} from '../shared/weaponAttachments.ts';
import {armorAttachmentEffects} from '../shared/armorAttachments.ts';
import {CARRIED_WEAPON_SLOTS,weaponFitsSlot} from '../shared/weaponSlots.ts';
import {stackWeight} from '../shared/fittedInventory.ts';
import {WEAPON_SLOT_LABELS,isFirearmSlot,compatibleWeaponSlots} from './weaponSlotUI';
import {ITEM_BY_ID,GOLD_OPTIONS,rarityColor,rarityLabel,type ItemDef} from '../shared/catalog';
import {itemArtwork} from './itemArtwork';
import {attachmentQualityFactor} from '../shared/attachmentQualities';
import './secureUI.css';
type Obj=Record<string,any>;
type Stack={itemId:string;quantity:number;fittings?:Record<string,string>};
type Direction='deposit'|'withdraw';
type GearSlot='armor'|'helmet'|'backpack'|'vest'|typeof CARRIED_WEAPON_SLOTS[number]|string;
type Selection={itemId:string;source:'bag'|'secure'|'equipped';slot?:string;armorSlot?:number};
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const amount=(value:unknown)=>Math.max(0,Number(value)||0);
const stacks=(value:unknown):Stack[]=>Array.isArray(value)?value.filter(entry=>entry&&typeof entry.itemId==='string'&&amount(entry.quantity)>0).map(entry=>({itemId:entry.itemId,quantity:Math.floor(amount(entry.quantity)),...(entry.fittings?{fittings:{...entry.fittings}}:{})})):[];
const labels:Record<string,string>={...WEAPON_SLOT_LABELS,armor:'방탄조끼',helmet:'헬멧',backpack:'배낭',vest:'방어구 파츠',scope:'조준경',barrel:'총구',grip:'손잡이',magazine:'탄창'};
const money=(value:number)=>new Intl.NumberFormat('ko-KR').format(value);
const armorSlots=(item?:ItemDef)=>item?Math.min(3,Math.max(1,Number((item as ItemDef&{armorSlots?:number}).armorSlots??1))):0;
const inspectDescription=(item?:ItemDef)=>item?.category==='weapon' ? `${item.name} · ${item.family??'Other'}` : item?.description??'';
/** In-raid inventory: renders private snapshots and dispatches existing intents only. */
export class SecureUI {
 private root:HTMLElement|null=null;private panel:HTMLElement|null=null;private open=false;private signature='';private player:Obj|null=null;private paused=false;
 private selected:Selection|null=null;private storageTab:'bag'|'secure'='bag';private mobileView='weapons';private activeArmorSlot=0;private filterVest=false;
 private pendingGear:{slot:GearSlot;itemId:string|null;armorSlot?:number}|null=null;private pendingTransfer:{source:'bag'|'secure';itemId:string;quantity:number}|null=null;private pendingDrop:{itemId:string;remaining:number;quantity:number}|null=null;private notice='';private timer=0;
 private readonly onKey=(event:KeyboardEvent)=>{if(event.key!=='Escape'||!this.open)return;event.stopPropagation();if(this.selected){this.selected=null;this.refresh();}else this.close();};
 constructor(private send:(type:string,data?:Obj)=>void){}
 get isOpen(){return this.open;}
 mount(parent:HTMLElement){
  window.removeEventListener('keydown',this.onKey,true);this.root?.remove();clearTimeout(this.timer);this.open=false;this.signature='';this.player=null;this.paused=false;this.selected=null;this.pendingGear=null;this.pendingTransfer=null;this.pendingDrop=null;this.notice='';this.storageTab='bag';this.mobileView='weapons';this.filterVest=false;
  this.root=document.createElement('div');this.root.className='secure-overlay';this.root.hidden=true;this.root.innerHTML='<section class="secure-panel" role="dialog" aria-modal="true" aria-labelledby="secure-title"></section>';this.panel=this.root.querySelector('.secure-panel');
  ['pointerdown','pointerup','click','dblclick','contextmenu','wheel'].forEach(type=>this.root!.addEventListener(type,event=>event.stopPropagation()));this.root.addEventListener('click',event=>{if(event.target===this.root)this.close();});parent.append(this.root);window.addEventListener('keydown',this.onKey,true);
 }
 toggle(){if(this.open)return this.close();if(!this.root||!this.player||this.paused||!this.canShow(this.player))return false;this.open=true;this.root.hidden=false;this.refresh();return true;}
 close(){if(!this.open)return false;this.open=false;this.selected=null;this.signature='';if(this.root)this.root.hidden=true;return true;}
 update(player:Obj,paused:boolean){
  this.player=player;this.paused=paused;
  if(this.pendingGear&&this.equippedId(player,this.pendingGear.slot,this.pendingGear.armorSlot)===this.pendingGear.itemId){this.pendingGear=null;clearTimeout(this.timer);this.notice='장착 변경 완료';this.signature='';}
  if(this.pendingTransfer&&this.sourceStacks(player,this.pendingTransfer.source).find(stack=>stack.itemId===this.pendingTransfer!.itemId)?.quantity!==this.pendingTransfer.quantity){this.pendingTransfer=null;clearTimeout(this.timer);this.notice='물품 이동 완료';this.signature='';}
  if(this.pendingDrop&&(this.sourceStacks(player,'bag').find(stack=>stack.itemId===this.pendingDrop!.itemId)?.quantity??0)<=this.pendingDrop.remaining){const quantity=this.pendingDrop.quantity;this.pendingDrop=null;clearTimeout(this.timer);this.notice=`${quantity}개를 바닥에 놓았습니다. 다시 획득할 수 있습니다.`;this.signature='';}
  if(!this.root)return;if(!this.canShow(player)){this.close();return;}this.root.hidden=paused||!this.open;if(this.open&&!paused)this.render(player);
 }
 private canShow(player:Obj){return !!player?.alive&&!player.downed&&!player.settled&&!player.boarded&&!player.extracted&&!player.raidEnded;}
 private refresh(){this.signature='';if(this.open&&this.player&&!this.paused)this.render(this.player);}
 private get busy(){return !!this.pendingGear||!!this.pendingTransfer||!!this.pendingDrop;}
 private equippedId(player:Obj,slot:string,index?:number):string|null{if(slot==='vest')return player.armorAttachments?.[index??0]??player.equipment?.[`armor:${index??0}`]??(index===0?player.equipment?.vest:null)??null;return player.equipment?.[slot]??null;}
 private sourceStacks(player:Obj,source:'bag'|'secure'){
  if(source==='secure')return stacks(player.secure);const merged=new Map<string,number>();stacks(player.inventory).forEach(stack=>merged.set(stack.itemId,(merged.get(stack.itemId)??0)+stack.quantity));Object.entries(player.reserveAmmo??{}).forEach(([id,qty])=>{if(amount(qty)>0)merged.set(id,(merged.get(id)??0)+Math.floor(amount(qty)));});return [...merged].map(([itemId,quantity])=>({itemId,quantity}));
 }
 private secureWeight(player:Obj){return stacks(player.secure).reduce((sum,stack)=>sum+stackWeight(stack,id=>ITEM_BY_ID[id]),0);}
 private render(player:Obj){
  if(!this.panel)return;
  const bag=this.sourceStacks(player,'bag'),secure=stacks(player.secure),signature=JSON.stringify([bag,secure,player.equipment,player.weaponAttachments,player.weaponFittingStats,player.armorAttachments,player.magazines,player.loadedAmmo,player.ammoInMagazine,player.activeWeaponSlot,player.carriedWeight,player.carryCapacity,player.secureCapacity,this.selected,this.storageTab,this.mobileView,this.activeArmorSlot,this.filterVest,this.pendingGear,this.pendingTransfer,this.pendingDrop,this.notice]);
  if(signature===this.signature)return;this.signature=signature;
  const focused=document.activeElement instanceof HTMLInputElement&&this.panel.contains(document.activeElement)?document.activeElement:null,focusKey=focused?.dataset.quantityKey,values=new Map<string,string>();this.panel.querySelectorAll<HTMLInputElement>('[data-quantity-key]').forEach(input=>values.set(input.dataset.quantityKey!,input.value));
  const scroll=new Map<string,number>();this.panel.querySelectorAll<HTMLElement>('[data-scroll]').forEach(element=>scroll.set(element.dataset.scroll!,element.scrollTop));
  this.panel.innerHTML=`<header class="inv-header"><div><span>LIVE EXPEDITION / FIELD INVENTORY</span><h2 id="secure-title">인벤토리</h2></div><button data-close aria-label="인벤토리 닫기" class="bc-field-inventory-close">×</button></header><nav class="inv-mobile-tabs" aria-label="인벤토리 영역">${[['equipment','장비'],['weapons','총기'],['storage','배낭 / 암호상자']].map(([view,title])=>`<button data-view="${view}" class="${this.mobileView===view?'active':''}">${title}</button>`).join('')}</nav><div class="inv-layout" data-view="${this.mobileView}">${this.equipmentColumn(player)}${this.weaponsColumn(player)}${this.storageColumn(player)}</div>${this.detail(player,values)}<footer class="inv-footer"><span>${this.busy?'서버 확인 중…':esc(this.notice)}</span><span><kbd>I</kbd> 인벤토리 · <kbd>ESC</kbd> 닫기</span></footer>`;
  this.panel.querySelector<HTMLButtonElement>('[data-close]')!.onclick=()=>this.close();this.panel.querySelector<HTMLButtonElement>('[data-detail-close]')?.addEventListener('click',()=>{this.selected=null;this.refresh();});
  this.panel.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(button=>button.onclick=()=>{this.mobileView=button.dataset.view!;this.refresh();});
  this.panel.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(button=>button.onclick=()=>{this.storageTab=button.dataset.tab as 'bag'|'secure';this.selected=null;this.filterVest=false;this.refresh();});
  this.panel.querySelectorAll<HTMLButtonElement>('[data-inspect]').forEach(button=>button.onclick=()=>{this.selected={itemId:button.dataset.inspect!,source:button.dataset.source as Selection['source'],slot:button.dataset.slot,armorSlot:button.dataset.armorSlot===undefined?undefined:Number(button.dataset.armorSlot)};this.refresh();});
  this.panel.querySelectorAll<HTMLButtonElement>('[data-armor-index]').forEach(button=>button.onclick=()=>{this.activeArmorSlot=Number(button.dataset.armorIndex);this.filterVest=true;this.storageTab='bag';this.mobileView='storage';this.refresh();});
  this.panel.querySelector<HTMLButtonElement>('[data-clear-filter]')?.addEventListener('click',()=>{this.filterVest=false;this.refresh();});
  this.panel.querySelectorAll<HTMLButtonElement>('[data-equip]').forEach(button=>button.onclick=()=>this.equipGear(button.dataset.equip as GearSlot,button.dataset.itemId??null,button.dataset.armorSlot===undefined?undefined:Number(button.dataset.armorSlot)));
  this.panel.querySelectorAll<HTMLButtonElement>('[data-equip-part]').forEach(button=>button.onclick=()=>this.equipWeaponPart(button.dataset.weaponSlot!,button.dataset.equipPart!,button.dataset.itemId??null));
  this.panel.querySelector<HTMLButtonElement>('[data-transfer]')?.addEventListener('click',()=>this.transfer());
  this.panel.querySelector<HTMLButtonElement>('[data-drop]')?.addEventListener('click',()=>this.drop());
  this.panel.querySelector<HTMLButtonElement>('[data-drop-equipped]')?.addEventListener('click',()=>this.dropEquipped());
  this.panel.querySelectorAll<HTMLInputElement>('input[type="range"][data-quantity-key]').forEach(input=>input.addEventListener('input',()=>{const output=input.closest('label')?.querySelector('[data-quantity-value]');if(output)output.textContent=input.value;input.setAttribute('aria-valuetext',input.value+'개 / 최대 '+input.max+'개');input.setCustomValidity('');}));
  this.panel.querySelectorAll<HTMLElement>('[data-scroll]').forEach(element=>element.scrollTop=scroll.get(element.dataset.scroll!)??0);
  if(focusKey)this.panel.querySelector<HTMLInputElement>(`[data-quantity-key="${CSS.escape(focusKey)}"]`)?.focus({preventScroll:true});
 }
 private equipmentColumn(player:Obj){
  const armor=ITEM_BY_ID[this.equippedId(player,'armor')??''],count=armorSlots(armor);this.activeArmorSlot=Math.min(this.activeArmorSlot,Math.max(0,count-1));
  return `<aside class="inv-equipment" data-scroll="equipment"><h3>현재 장비</h3>${(['helmet','armor','backpack'] as const).map(slot=>{const id=this.equippedId(player,slot),item=id?ITEM_BY_ID[id]:undefined;return `<article class="inv-protection"><span>${labels[slot]}</span><button class="inv-equipment-tile" style="--rarity:${item?rarityColor(item):'#65707a'}" data-inspect="${esc(id??'')}" data-source="equipped" data-slot="${slot}" ${!item?'disabled':''}>${itemArtwork(item)}<small>${item?esc(rarityLabel(item)):'미장착'}</small></button><strong>${esc(item?.name??'빈 슬롯')}</strong>${slot==='armor'?`<div class="inv-armor-fittings" aria-label="방어구 파츠 슬롯">${Array.from({length:count},(_,index)=>{const fittingId=this.equippedId(player,'vest',index),fitting=fittingId?ITEM_BY_ID[fittingId]:undefined;return `<button ${fitting?`data-inspect="${esc(fittingId!)}" data-source="equipped" data-slot="vest" data-armor-slot="${index}"`:`data-armor-index="${index}"`} title="${fitting?esc(fitting.name):'방어구 파츠 선택'}" class="${this.filterVest&&this.activeArmorSlot===index?'active':''}" style="--rarity:${fitting?rarityColor(fitting):'#68737d'}">${fitting?itemArtwork(fitting):'<b>+</b>'}<small>${index+1}</small></button>`;}).join('')}</div>`:''}</article>`;}).join('')}</aside>`;
 }
 private weaponsColumn(player:Obj){
  return `<section class="inv-weapons" data-scroll="weapons"><h3 class="inv-section-label">무기 · 장착 상태</h3>${CARRIED_WEAPON_SLOTS.map(slot=>{const id=this.equippedId(player,slot),weapon=id?ITEM_BY_ID[id]:undefined,active=player.activeWeaponSlot===slot,mag=player.magazines?.[slot],rounds=typeof mag==='number'?String(mag):mag&&typeof mag==='object'?String(mag.ammo??mag.rounds??'—'):active?String(player.ammoInMagazine??'—'):'—',ammoId=player.loadedAmmo?.[slot]??weapon?.ammo,reserve=amount(player.reserveAmmo?.[ammoId??'']);return `<article class="inv-weapon" style="--rarity:${weapon?rarityColor(weapon):'#65707a'}"><header><div><span>${labels[slot]}</span><strong>${esc(weapon?.name??'총기 미장착')}</strong></div><div class="inv-ammo"><small>${esc(weapon?.caliber??ITEM_BY_ID[weapon?.ammo??'']?.name??'')}</small><b>${weapon?rounds:'—'} <i>/ ${weapon?reserve:'—'}</i></b></div></header><div class="inv-weapon-stage"><button class="inv-gun-image" data-inspect="${esc(id??'')}" data-source="equipped" data-slot="${slot}" ${!weapon?'disabled':''}>${itemArtwork(weapon)}</button>${(isFirearmSlot(slot)?['scope','barrel','grip','magazine'] as const:[]).map(part=>{const partId=player.weaponAttachments?.[slot]?.[part]??player.equipment?.[`${slot}:${part}`],fitting=ITEM_BY_ID[partId??''],supported=weapon?.weaponSlots?.includes(part);return `<button class="inv-weapon-fitting fitting-${part} ${!supported?'unsupported':''}" style="--rarity:${fitting?rarityColor(fitting):'#6b7782'}" data-inspect="${esc(partId??'')}" data-source="equipped" data-slot="${slot}:${part}" title="${fitting?esc(fitting.name):labels[part]}" ${!fitting?'disabled':''}>${fitting?itemArtwork(fitting):`<span>${supported?labels[part]:'—'}</span>`}</button>`;}).join('')}</div><div class="inv-weapon-grade">${weapon?esc(rarityLabel(weapon)):'미장착'} <span>현재 장착 상태</span></div></article>`;}).join('')}</section>`;
 }
 private storageColumn(player:Obj){
  const secure=this.storageTab==='secure',source=secure?'secure':'bag',all=this.sourceStacks(player,source),items=this.filterVest&&!secure?all.filter(stack=>ITEM_BY_ID[stack.itemId]?.slot==='vest'):all,weight=secure?this.secureWeight(player):amount(player.carriedWeight),capacity=secure?amount(player.secureCapacity??40):amount(player.carryCapacity??150);
  return `<aside class="inv-storage"><nav class="inv-storage-tabs"><button data-tab="bag" class="${!secure?'active':''}">배낭</button><button data-tab="secure" class="${secure?'active':''}">암호상자</button></nav><header><h3>${this.filterVest&&!secure?'방어구 호환 파츠':secure?'암호상자':'배낭 내용물'}</h3><b>${weight.toFixed(1)} <small>/ ${capacity} 용량</small></b></header><div class="inv-capacity-track"><i style="width:${capacity?Math.min(100,weight/capacity*100):0}%"></i></div><p class="inv-storage-hint">${this.filterVest?`방어구 파츠 슬롯 ${this.activeArmorSlot+1} 선택`:'물품을 선택해 이동·장착하거나 바닥에 놓으세요'}${this.filterVest?'<button data-clear-filter>전체 보기 ×</button>':''}</p><div class="inv-item-grid" data-scroll="storage">${items.map(stack=>{const item=ITEM_BY_ID[stack.itemId];if(!item)return '';return `<button class="inv-item-tile ${this.selected?.itemId===item.id&&this.selected.source===source?'selected':''}" style="--rarity:${rarityColor(item)}" data-inspect="${esc(item.id)}" data-source="${source}">${rarityLabel(item)?`<span class="inv-tile-grade">${esc(rarityLabel(item))}</span>`:''}${itemArtwork(item)}<strong>${esc(item.name)}</strong><span class="inv-tile-bottom"><small>${item.weight} 용량</small><b>×${stack.quantity}</b></span></button>`;}).join('')||`<div class="inv-empty"><b>${this.filterVest?'호환 파츠가 없습니다':secure?'암호상자가 비었습니다':'배낭이 비었습니다'}</b><span>${secure?'빈 공간에 전리품을 보호하세요':'획득한 물품이 여기에 표시됩니다'}</span></div>`}</div></aside>`;
 }
 private detail(player:Obj,values:Map<string,string>){
  const selection=this.selected;if(!selection)return '';const item=ITEM_BY_ID[selection.itemId];if(!item)return '';
  const source=selection.source,quantity=source==='equipped'?1:this.sourceStacks(player,source).find(stack=>stack.itemId===item.id)?.quantity??0,key=`${source}:${item.id}`,room=source==='bag'?Math.max(0,amount(player.secureCapacity??40)-this.secureWeight(player)):Math.max(0,amount(player.carryCapacity??150)-amount(player.carriedWeight)),max=source==='equipped'?0:Math.max(0,Math.min(quantity,item.weight>0?Math.floor((room+1e-6)/item.weight):quantity)),preserved=Number(values.get(key)),value=Number.isSafeInteger(preserved)&&preserved>0&&preserved<=max?preserved:Math.max(1,max);
  const options=(item.optionIds??[]).map(id=>GOLD_OPTIONS[id]).filter(Boolean),fields:[[string,string],...[string,string][]]=[['점유 용량',String(item.weight)],['판매가',money(item.sell??0)+' ◈']];
  if(item.damage)fields.push(['기본 피해량',String(item.damage)]);if(item.range)fields.push(['기본 사거리',item.range+' m']);if(item.magazine)fields.push(['기본 탄창',item.magazine+' 발']);if(item.capacity)fields.push(['추가 배낭 용량',String(item.capacity)]);if(item.reduction!==undefined)fields.push(['기본 피해 감소',(item.reduction*100).toFixed(1)+'%']);if(item.durability)fields.push(['기준 내구도',String(item.durability)]);if(source==='equipped'&&selection.slot==='armor'&&Number.isFinite(player.fittedWeights?.armor))fields.push(['파츠 포함 장비 중량',String(player.fittedWeights.armor)]);
  const fitting=source==='equipped'&&isFirearmSlot(selection.slot??'')?player.weaponFittingStats?.[selection.slot!]:null;
  if(fitting){if(Number.isFinite(fitting.magazineCapacity))fields.push(['장착 후 탄창',fitting.magazineCapacity+' 발']);if(Number.isFinite(fitting.reloadSeconds))fields.push(['장착 후 재장전',Number(fitting.reloadSeconds).toFixed(2)+' 초']);if(Number.isFinite(fitting.range))fields.push(['장착 후 사거리',Number(fitting.range).toFixed(1)+' m']);if(item.spread!==undefined&&Number.isFinite(fitting.spreadMultiplier))fields.push(['장착 후 탄퍼짐',(item.spread*fitting.spreadMultiplier).toFixed(3)]);}
  if(item.category==='attachment'&&item.effect==='capacity')fields.push(['파츠 추가 용량',String(10*attachmentQualityFactor(item))]);
  return `<aside class="inv-detail" role="dialog" aria-label="${esc(item.name)} 상세" style="--rarity:${rarityColor(item)}"><header><div>${itemArtwork(item)}</div><section>${rarityLabel(item)?`<span>${esc(rarityLabel(item))}</span>`:''}<h3>${esc(item.name)}</h3><small>${source==='equipped'?'현재 장착':source==='secure'?'암호상자':'배낭'} · ×${quantity}</small></section><button data-detail-close aria-label="아이템 상세 닫기">×</button></header><div class="inv-detail-content" data-scroll="detail"><p>${esc(inspectDescription(item))}</p>${options.length?`<section class="inv-item-options"><h4>장비 옵션</h4>${options.map(option=>`<div><b>${esc(option.name)}</b><span>${esc(option.description)}</span></div>`).join('')}</section>`:''}<dl>${fields.map(([label,value])=>`<div><dt>${label}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl><small class="inv-spec-note">내구도는 기준 사양이며 현재 내구도를 나타내지 않습니다. 피해 감소는 기본 장비 수치입니다.</small></div><footer>${source!=='equipped'?`<div class="inv-detail-transfer">${this.quantitySlider("이동 수량",key,max,value)}<button data-transfer ${max&&!this.busy?'':'disabled'}>${max?(source==='bag'?'암호상자 보관':'배낭으로 꺼내기'):'이동 공간 부족'}</button></div>`:''}${this.gearActions(player,item,selection)}${this.dropActions(player,selection,values)}<span class="inv-detail-status" role="status">${this.busy?'서버 확인 중…':esc(this.notice)}</span></footer></aside>`;
 }
 private quantitySlider(label:string,key:string,max:number,value:number,drop=false){
  const limit=Math.max(0,Math.floor(max)),current=limit?Math.max(1,Math.min(limit,value)):0;
  return `<label class="inv-quantity-slider"><span>${label}<output><b data-quantity-value>${current}</b> / ${limit}</output></span><input ${drop?'data-drop-quantity':''} data-quantity-key="${esc(key)}" type="range" min="${limit?1:0}" max="${limit}" step="1" value="${current}" ${limit&&!this.busy?'':'disabled'} aria-label="${label}" aria-valuetext="${current}개 / 최대 ${limit}개"><small><span>${limit?1:0}</span><span>최대 ${limit}</span></small></label>`;
 }
 private dropActions(player:Obj,selection:Selection,values:Map<string,string>){
  const selectedItem=ITEM_BY_ID[selection.itemId];if(selection.source==='equipped'&&selectedItem?.category==='weapon'&&CARRIED_WEAPON_SLOTS.includes(selection.slot as any))return `<div class="inv-detail-drop"><div><button data-drop-equipped ${this.busy?'disabled':''}>착용 중인 무기 바로 버리기</button></div><small>무기와 장착 파츠가 한 묶음으로 바닥에 남습니다.</small></div>`;
  if(selection.source!=='bag')return '';const quantity=this.sourceStacks(player,'bag').find(stack=>stack.itemId===selection.itemId)?.quantity??0,key='drop:'+selection.itemId,preserved=Number(values.get(key)),value=Number.isSafeInteger(preserved)&&preserved>=1&&preserved<=quantity?preserved:1;
  return `<div class="inv-detail-drop"><div>${this.quantitySlider("버릴 수량",key,quantity,value,true)}<button data-drop ${quantity&&!this.busy?'':'disabled'}>바닥에 버리기</button></div><small>바닥에 놓은 물품은 나와 동료가 다시 획득할 수 있습니다.</small></div>`;
 }
 private dropEquipped(){
  if(!this.player||this.busy||this.selected?.source!=='equipped'||!this.selected.slot)return;const slot=this.selected.slot;this.pendingGear={slot,itemId:null};this.notice='';this.send('drop_equipped',{slot});this.selected=null;this.waitForServer();this.refresh();
 }
 private drop(){
  if(!this.player||this.busy||this.selected?.source!=='bag')return;const input=this.panel?.querySelector<HTMLInputElement>('[data-drop-quantity]');if(!input)return;
  const itemId=this.selected.itemId,quantity=Number(input.value),available=this.sourceStacks(this.player,'bag').find(stack=>stack.itemId===itemId)?.quantity??0;
  if(!Number.isSafeInteger(quantity)||quantity<1||quantity>available){input.setCustomValidity('보유 수량 내에서 정수를 선택하세요.');input.reportValidity();input.oninput=()=>input.setCustomValidity('');return;}
  this.pendingDrop={itemId,remaining:available-quantity,quantity};this.notice='';this.send('drop_inventory',{itemId,quantity});this.waitForServer();this.refresh();
 }
 /** Called by the host when an authoritative action error arrives. */
 rejectPending(message:string){if(!this.busy)return;this.pendingGear=null;this.pendingTransfer=null;this.pendingDrop=null;clearTimeout(this.timer);this.notice=message;this.refresh();}
 private gearProjection(player:Obj,slot:GearSlot,itemId:string|null,index?:number){
  const oldId=this.equippedId(player,slot,index),old=ITEM_BY_ID[oldId??''],next=itemId?ITEM_BY_ID[itemId]:undefined;let occupied=amount(player.carriedWeight)-amount(next?.weight)+amount(old?.weight),capacity=amount(player.carryCapacity??150);
  if(CARRIED_WEAPON_SLOTS.some(s=>s===slot)){const selected=stacks(player.inventory).find(s=>s.itemId===itemId),oldParts=isFirearmSlot(slot)?Object.values(player.weaponAttachments?.[slot]??{}).reduce<number>((sum,id)=>sum+amount(ITEM_BY_ID[String(id)]?.weight),0):0;occupied+=oldParts-(selected?stackWeight({...selected,quantity:1},id=>ITEM_BY_ID[id])-amount(next?.weight):0);if(isFirearmSlot(slot)){const ammoId=player.loadedAmmo?.[slot]??old?.ammo;occupied+=amount(player.magazines?.[slot])*amount(ITEM_BY_ID[ammoId??'']?.weight);}}
  if(slot==='backpack')capacity+=amount(next?.capacity)-amount(old?.capacity);
  if(slot==='vest')capacity+=(next?.effect==='capacity'?10*attachmentQualityFactor(next):0)-(old?.effect==='capacity'?10*attachmentQualityFactor(old):0);
  if(slot==='armor'){const selected=stacks(player.inventory).find(s=>s.itemId===itemId),oldParts=[0,1,2].map(part=>this.equippedId(player,'vest',part));occupied+=oldParts.reduce((sum,id)=>sum+amount(ITEM_BY_ID[id??'']?.weight),0)-(selected?stackWeight({...selected,quantity:1},id=>ITEM_BY_ID[id])-amount(next?.weight):0);const oldGear={armor:oldId,...Object.fromEntries(oldParts.map((id,part)=>[`armor:${part}`,id]))},newGear={armor:itemId,...Object.fromEntries(Object.entries(selected?.fittings??{}).map(([part,id])=>[`armor:${part}`,id]))};capacity+=armorAttachmentEffects(newGear,id=>ITEM_BY_ID[id]).capacity-armorAttachmentEffects(oldGear,id=>ITEM_BY_ID[id]).capacity;}
  const inBackpack=itemId===null||stacks(player.inventory).some(stack=>stack.itemId===itemId);if(oldId===itemId)return {occupied:amount(player.carriedWeight),capacity:amount(player.carryCapacity??150),fits:amount(player.carriedWeight)<=amount(player.carryCapacity??150)+1e-6,inBackpack,oldId};return {occupied:Math.max(0,occupied),capacity:Math.max(0,capacity),fits:occupied<=capacity+1e-6,inBackpack,oldId};
 }
 private gearActions(player:Obj,item:ItemDef,selection:Selection){
  if(selection.source==='secure')return '';
  if(item.category==='attachment'&&item.slot!=='vest'){const current=selection.source==='equipped'&&selection.slot?.includes(':')?selection.slot.split(':'):null,targets=current?[current[0]]:CARRIED_WEAPON_SLOTS.filter(slot=>{const host=ITEM_BY_ID[this.equippedId(player,slot)??''];return isFirearmSlot(slot)&&host&&supportsWeaponAttachment(host,item);});return targets.map(slot=>{const host=ITEM_BY_ID[this.equippedId(player,slot)??''],compatible=selection.source==='equipped'||(host&&supportsWeaponAttachment(host,item)),itemId=selection.source==='equipped'?null:item.id;return `<div class="inv-gear-controls"><button data-equip-part="${item.slot}" data-weapon-slot="${slot}" ${itemId?`data-item-id="${esc(itemId)}"`:''} ${this.busy||!compatible?'disabled':''}>${labels[slot]} · ${labels[item.slot??'']??item.name} ${selection.source==='equipped'?'해제':this.equippedId(player,slot+':'+item.slot)?'교체':'장착'}</button><span>전투 중 즉시 교체</span></div>`;}).join('');}
  if(item.category==='weapon'){const targets=selection.source==='equipped'&&selection.slot?CARRIED_WEAPON_SLOTS.filter(s=>s===selection.slot):compatibleWeaponSlots(item);return targets.map(slot=>{const itemId=selection.source==='equipped'?null:item.id,p=this.gearProjection(player,slot,itemId),disabled=this.busy||!p.fits||!p.inBackpack;return `<div class="inv-gear-controls"><button data-equip="${slot}" ${itemId?`data-item-id="${esc(itemId)}"`:''} ${disabled?'disabled':''}>${labels[slot]} ${selection.source==='equipped'?'장착 해제':p.oldId?'교체 장착':'장착'}</button><span class="${p.fits?'':'over'}">변경 후 배낭 ${p.occupied.toFixed(1)} / ${p.capacity.toFixed(1)} 용량</span></div>`;}).join('');}
  const gear=['armor','helmet','backpack'].includes(item.category)?item.category as GearSlot:item.slot==='vest'?'vest':null;if(!gear)return '';
  const armorCount=armorSlots(ITEM_BY_ID[this.equippedId(player,'armor')??'']),index=gear==='vest'?(selection.armorSlot??this.activeArmorSlot):undefined,itemId=selection.source==='equipped'?null:item.id,projection=this.gearProjection(player,gear,itemId,index),supported=gear!=='vest'||armorCount>0,already=selection.source!=='equipped'&&projection.oldId===itemId,disabled=this.busy||!projection.fits||!projection.inBackpack||!supported||already;
  return `${gear==='vest'&&selection.source==='bag'?`<nav class="inv-part-index" aria-label="장착할 방어구 파츠 슬롯">${Array.from({length:armorCount},(_,part)=>`<button data-armor-index="${part}" class="${part===index?'active':''}">슬롯 ${part+1}</button>`).join('')}</nav>`:''}<div class="inv-gear-controls"><button data-equip="${gear}" ${itemId?`data-item-id="${esc(itemId)}"`:''} ${index===undefined?'':`data-armor-slot="${index}"`} ${disabled?'disabled':''}>${!supported?'방탄조끼를 먼저 장착':already?'같은 장비 장착 중':!projection.fits?'장착 공간 부족':selection.source==='equipped'?'장착 해제':projection.oldId?'교체 장착':'장착'}</button><span class="${projection.fits?'':'over'}">변경 후 배낭 ${projection.occupied.toFixed(1)} / ${projection.capacity.toFixed(1)} 용량</span></div>`;
 }
 private equipWeaponPart(weaponSlot:string,part:string,itemId:string|null){
  if(!this.player||this.busy||!['primary','secondary','pistol'].includes(weaponSlot)||!['scope','barrel','grip','magazine'].includes(part))return;const current=this.equippedId(this.player,weaponSlot+':'+part);if(!itemId&&!current)return;
  this.pendingGear={slot:weaponSlot+':'+part,itemId};this.notice='';this.send('equip_raid',{slot:part,itemId,weaponSlot});this.waitForServer();this.refresh();
 }
 private equipGear(slot:GearSlot,itemId:string|null,index?:number){
  if(!this.player||this.busy)return;if(itemId&&CARRIED_WEAPON_SLOTS.some(s=>s===slot)&&!weaponFitsSlot(ITEM_BY_ID[itemId],slot))return;const projection=this.gearProjection(this.player,slot,itemId,index);if(!projection.fits||!projection.inBackpack||itemId===null&&!projection.oldId)return;
  this.pendingGear={slot,itemId,armorSlot:index};this.notice='';this.send('equip_raid',{slot,itemId,...(slot==='vest'?{armorSlot:index}: {})});this.waitForServer();this.refresh();
 }
 private transfer(){
  if(!this.selected||this.busy||!this.player||this.selected.source==='equipped')return;const input=this.panel?.querySelector<HTMLInputElement>('[data-quantity-key]');if(!input)return;const quantity=Number(input.value);if(!Number.isSafeInteger(quantity)||quantity<1||quantity>Number(input.max)){input.reportValidity();return;}
  const source=this.selected.source,itemId=this.selected.itemId,available=this.sourceStacks(this.player,source).find(stack=>stack.itemId===itemId)?.quantity??0;this.pendingTransfer={source,itemId,quantity:available};this.notice='';this.send('secure_transfer',{itemId,quantity,direction:(source==='bag'?'deposit':'withdraw') as Direction});this.waitForServer();this.refresh();
 }
 private waitForServer(){clearTimeout(this.timer);this.timer=window.setTimeout(()=>{this.pendingGear=null;this.pendingTransfer=null;this.pendingDrop=null;this.notice='변경되지 않았다면 다시 시도하세요.';this.refresh();},1800);}
}
